### ISSUE TITLE
Webpack 2 update?

### ISSUE THREAD

**Issue by fremfi** [developit/preact-boilerplate#107] opened 2017-01-18 01:51 UTC

**Comment by developit** [comment] 2017-01-18 18:01
It's on the todo list now! We'll use this issue to track progress.

**Comment by AdamJo** [comment] 2017-02-02 04:51
I'm using this boilerplate for a project and attempted to update to Webpack 2.  

@developit I'll leave the [Forked version here](https://github.com/AdamJo/preact-boilerplate/commit/c00d6833c5399c64b5e9e2b5bc6d5b2f1e856436) in case you may want to reference the changes.

One issue has popped up so far.  The class names are not being imported correctly in the `/src/components/`. It seems `import style from "./styles.less"` is returning an empty object.  The classes are in the build file correctly which means it is loading them but it is not getting to the index.js files. This may be an issue with `extract-text-webpack-plugin` since it is still in RC and has a few issues right now.

All of the .less files in the `/style` folder (global) seem to be loading fine.

Besides that, everything else seems to compile correctly.

**Comment by developit** [comment] 2017-02-02 12:37
Nice! I'll check your fork and see if I can fix.

**Comment by bmatzner** [comment] 2017-03-04 15:38
@AdamJo enable css modules extraction via the modules option on the css-loader in your webpack config:
`
…
            {
              loader: 'css-loader',
              options: {
                modules: true,
                sourceMap: true,
              }
            }
`

**Comment by AdamJo** [comment] 2017-03-04 22:21
Sorry for not following up on this. @bmatzner thanks for the catching that.

@developit I have made a new fork and updated from master.  Webpack and Webpack-Dev-Server upgrade to version 2 and working as intended.  Each commit has a link to the migration notes on webpack.js.org and some details.  Let me know if you want me to open a pull request.

[preact-boilerplate webpack 2 fork](https://github.com/AdamJo/preact-boilerplate)

**Comment by developit** [comment] 2017-03-05 03:34
Awesome, I will take a peek at this tomorrow. If the bundle size doesn't get larger and everything still works, we can merge it and get everyone using webpack 2 :)

**Comment by AdamJo** [comment] 2017-03-28 17:21
@developit I never heard back so I've just been keeping the boilerplate updated.  The bundle sizes are the same.

bundle.js: 7.3kb both
style.css: 887b both
`npm run test` and `npm run lint` are working as intended.

Let me know if you would want me to open a PR to merge it.

**Comment by developit** [comment] 2017-03-28 18:50
Definitely, let's get a PR in. I don't see any good reason to stay on Webpack 1 if the sizes are the same!

**Comment by AdamJo** [comment] 2017-03-28 19:06
Sounds good. The [PR can be found here](https://github.com/developit/preact-boilerplate/pull/157).

**Comment by ry5n** [comment] 2017-05-21 18:00
Since #158 was merged it looks like this can be closed.

**Comment by developit** [comment] 2017-05-23 14:19
Yup!

**Closed by developit** 2017-05-23 14:19 UTC
